[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
dotenv = "0.15"
env_logger = "0.9"
anyhow = "1.0"
jsonwebtoken = "8.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.5"